Build fix, test reporting added to github action

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -27,7 +27,19 @@ jobs:
     - name: Build
       run: dotnet build --configuration Release --no-restore
     - name: Test
-      run: dotnet test --verbosity normal
+      run: dotnet test --verbosity normal --logger="trx;logfilename=TestResults.trx" #--verbosity normal
+    - name: Reporting
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: 'Test results report'
+        reporter: 'dotnet-trx'
+        path: '**/TestResults/TestResults.trx'
+        only-summary: 'true'
+        max-annotations: '10'
+        fail-on-error: 'true'
+        list-suites: 'failed'
+        list-tests: 'failed'
     - name: Pack Data
       run: dotnet pack Atom.Data/Atom.Data.csproj --configuration Release
     - name: Pack Infrastructure
